name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: linux

    steps:
    - uses: actions/checkout@master

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Settings on System
      working-directory: ${{github.workspace}}
      run: cp ${{github.workspace}}/config.txt /boot/config.txt
      
    - name: Install Software to System
      working-directory: ${{github.workspace}}
      run: cp ${{github.workspace}}/build/SingleAPM /etc/SingleAPM
      
    - name: Install Config to System
      working-directory: ${{github.workspace}}
      run: cp ${{github.workspace}}/APMconfig.json /etc/APMconfig.json
      
